/**
 * STRICT ORDER STATUS CONFIGURATION
 * 
 * Defines the mandatory POS order lifecycle:
 * CREATED -> KOT_SENT -> PREPARING -> READY -> SERVED
 */

const ORDER_STATUS = {
    PENDING: 'PENDING',
    CREATED: 'CREATED',
    KOT_SENT: 'KOT_SENT',
    PREPARING: 'PREPARING',
    READY: 'READY',
    SERVED: 'SERVED',
    COMPLETED: 'COMPLETED',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED',
    ARCHIVED: 'ARCHIVED'
};

const STATUS_FLOW = {
    [ORDER_STATUS.PENDING]: [ORDER_STATUS.CREATED, ORDER_STATUS.KOT_SENT, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.CREATED]: [ORDER_STATUS.KOT_SENT, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.KOT_SENT]: [ORDER_STATUS.PREPARING, ORDER_STATUS.READY, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.PREPARING]: [ORDER_STATUS.READY, ORDER_STATUS.SERVED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.READY]: [ORDER_STATUS.SERVED, ORDER_STATUS.COMPLETED, ORDER_STATUS.CLOSED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.SERVED]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.CLOSED, ORDER_STATUS.CANCELLED],
    [ORDER_STATUS.COMPLETED]: [ORDER_STATUS.ARCHIVED],
    [ORDER_STATUS.CLOSED]: [ORDER_STATUS.ARCHIVED],
    [ORDER_STATUS.CANCELLED]: [],
    [ORDER_STATUS.ARCHIVED]: []
};

module.exports = {
    ORDER_STATUS,
    STATUS_FLOW
};
